#ifndef WATCHLEDBOARD_H
#define WATCHLEDBOARD_H

#define BOARDCHIPMAX 4
#define BOARDCHIPMEMLEN 32

#define BOARDMEMLEN 128 // 4 * 32

#define BOARDCHIPCOLORMEM 16

#define SECPOS 60
#define MINPOS 60
#define HOURPOS 30

#define BOARDCHIPGREENMEMSTART 0
#define BOARDCHIPREDMEMSTART 16

#define COLOR_GREEN     0x01
#define COLOR_RED       0x02
#define COLOR_YELOW     0x03




#endif
